### ISSUE TITLE
Problem, can you help ?

### ISSUE THREAD

**Issue by Heroes84** [anton-pavlov/homm3_docker#1]
Hi I follow you nice tutorial but when I want testing i getting a error:
`Unable to find image 'wine:latest' locally
docker: Error response from daemon: pull access denied for wine, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.`

I check that wine:latest image doesn't exists ?
wine/sources/homm3_docker  master ✔                                                                                                                       91d  ⍉
▶ docker search wine:latest
NAME                DESCRIPTION         STARS               OFFICIAL            AUTOMATED

**Comment by devkpv** [comment]
@Heroes84 Wine is local image from README.md preparation step. You did it?

**Comment by Heroes84** [comment]
@SpiLLeR Thanks for you replay ! When i build docker container I have fallowing error:

> Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

> The following packages have unmet dependencies:
 winehq-stable : Depends: wine-stable (= 5.0.0~bionic)
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update && apt-get install -y     winehq-stable 	alsa-utils 	libasound2 	libasound2-plugins 	pulseaudio 	pulseaudio-utils' returned a non-zero code: 100

Next I run sound test:
> ▶ ./sound_test.sh
++ uname
+ '[' Darwin == Darwin ']'
+ which xquartz
+ xhost
+ grep INET:localhost
+ which pulseaudio
++ pwd
++ pwd
+ docker run -it --rm --env=DISPLAY=host.docker.internal:0 --env=PULSE_SERVER=host.docker.internal:4713 --volume=/tmp/.X11-unix:/tmp/.X11-unix:ro --volume=/Users/user/wine/sources/homm3_docker/.wine:/root/.wine --volume=/Users/user/wine/sources/homm3_docker/sources:/root/sources --volume=/Users/user/.config/pulse:/root/.config/pulse --hostname=winecellar --name=wine --privileged wine speaker-test
Unable to find image 'wine:latest' locally
docker: Error response from daemon: pull access denied for wine, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

Im not hearing any noise from my mac :( So I think that problem is in install winehq on container, can you check that all works fine for you ?

**Comment by anton-pavlov** [comment]
@Heroes84 I will check today and make fixes

**Comment by anton-pavlov** [comment]
@Heroes84 
Bug fixed in #2 and merged to master =)
Sorry for the delay

I checked everything on my macbook and it worked
<img width="1287" alt="Снимок экрана 2020-04-19 в 02 59 53" src="https://user-images.githubusercontent.com/5230575/79674358-12be9900-81eb-11ea-927a-f88aba48ff61.png">

**Comment by Heroes84** [comment]
@anton-pavlov Thank you for update the repo, now docker properly build image and tagged it as a wine
▶ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
wine                latest              920808e96eb3        50 minutes ago      1.48GB
ubuntu              18.04               4e5021d210f6        4 weeks ago         64.2MB

Sound test make noise cool ! But i have some issue with x11 test:
~/wine
▶ ./x11_test.sh
++ uname
+ '[' Darwin == Darwin ']'
+ which xquartz
+ xhost
+ grep INET:localhost
+ which pulseaudio
++ pwd
++ pwd
+ docker run -it --rm --env=DISPLAY=host.docker.internal:0 --env=PULSE_SERVER=host.docker.internal:4713 --volume=/tmp/.X11-unix:/tmp/.X11-unix:ro --volume=/Users/radoslawwawrzyniak/wine/.wine:/root/.wine --volume=/Users/radoslawwawrzyniak/wine/sources:/root/sources --volume=/Users/radoslawwawrzyniak/.config/pulse:/root/.config/pulse --hostname=winecellar --name=wine --privileged wine wine notepad.exe
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
0009:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0009:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.

So from log I'm understand, that I must install a libpng12-0 ?
▶ which libpng12-0
libpng12-0 not found

~/wine                                                                                                                        ⍉
▶ brew search libpng
==> Formulae
libpng 

So I'm install libpng using brew:
~/wine                                                                                                                        ⍉
▶ brew install libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.37.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/c8/c8e74da602c21f978cd7ee3d489979b4fc6681e71f678a1d99012943ee3a909f?__gda__=exp=
######################################################################## 100.0%
==> Pouring libpng-1.6.37.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.37: 27 files, 1.2MB

Now when is installed, try one more time run x11 test, but which no luck ;(
~/wine
▶ ./x11_test.sh
++ uname
+ '[' Darwin == Darwin ']'
+ which xquartz
+ xhost
+ grep INET:localhost
+ which pulseaudio
++ pwd
++ pwd
+ docker run -it --rm --env=DISPLAY=host.docker.internal:0 --env=PULSE_SERVER=host.docker.internal:4713 --volume=/tmp/.X11-unix:/tmp/.X11-unix:ro --volume=/Users/radoslawwawrzyniak/wine/.wine:/root/.wine --volume=/Users/radoslawwawrzyniak/wine/sources:/root/sources --volume=/Users/radoslawwawrzyniak/.config/pulse:/root/.config/pulse --hostname=winecellar --name=wine --privileged wine wine notepad.exe
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005
000d:err:menubuilder:convert_to_native_icon error 0x80004005 creating bitmap encoder
000d:err:wincodecs:PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0
000d:fixme:ole:CoCreateInstanceEx no instance created for interface {00000103-a8f2-4877-ba0a-fd2b6645fb94} of class {27949969-876a-41d7-9447-568f6a35a4dc}, hres is 0x80004005    
---- rest deleted ----

I have the same error `PngEncoder_CreateInstance Failed writing PNG because unable to find libpng12.so.0  ` even if previously installed libpng ? Of course I'm have running XQuartz. So please tell wht I need install on my macbook to run x11 test properly ?

**Comment by anton-pavlov** [comment]
@Heroes84 I also have this problem but wine is working
Wait 10 min and I add libpng to Dockerfile

**Comment by anton-pavlov** [comment]
@Heroes84 
libpng errors is fixed 

 - rebuild docker image 
 - start XQuartz
 - check that Enable connections from client networks flag is enabled is XQuarta preferences
 - start ./x11_test.sh - do you see wine dialogs or notepad?

**Comment by anton-pavlov** [comment]
XQuarts settings example 
<img width="891" alt="Снимок экрана 2020-04-19 в 17 26 27" src="https://user-images.githubusercontent.com/5230575/79690425-fbbb8d80-8262-11ea-825a-6f170554bebe.png">

**Comment by anton-pavlov** [comment]
XQuarts settings example
<img width="875" alt="Снимок экрана 2020-04-19 в 17 27 56" src="https://user-images.githubusercontent.com/5230575/79690458-27d70e80-8263-11ea-84ec-689a37073b93.png">

**Comment by Heroes84** [comment]
Yeah finally installation run ! Thank you @anton-pavlov for helping ! Last question about install heroes 3 setup from GOG (Hota requires Heroes 3 complete version I have this version from the GOG.com) How provide bin file from sources to the instalator application ? Example I copied setup_h3.exe and setup_h3.bin files to sources folder, second I started docker container and see that the docker shell (after executing setup_h3.exe) requires bin files but cannot locate it.
<img width="984" alt="Zrzut ekranu 2020-04-19 o 20 27 59" src="https://user-images.githubusercontent.com/5124243/79696596-dbe59300-827d-11ea-86b5-542c9b528ffc.png">

Inside docker container:

```
 root@winecellar:~# ll sources
 total 1230532
 drwxr-xr-x 6 root root        192 Apr 19 18:31 ./
 drwx------ 1 root root       4096 Apr 19 18:32 ../
 -rw-r--r-- 1 root root       8196 Apr 19 18:29 .DS_Store
 -rw-r--r-- 1 root root  247338218 Apr  9 19:10 HotA_1.6.1_setup.exe
 -rw-r--r-- 1 root root 1005040617 Apr 19 18:26 setup_h3.bin
 -rw-r--r-- 1 root root     822520 Apr 19 18:25 setup_h3.exe
 root@winecellar:~#
```

<img width="984" alt="Zrzut ekranu 2020-04-19 o 20 43 35" src="https://user-images.githubusercontent.com/5124243/79696669-7ba32100-827e-11ea-89fb-a35976bb96e2.png">

I also tired copy setup_h3.bin to .wine/drive_c/user folder and restart container, but also installator app don't see file in that location (C:\user)

**Comment by anton-pavlov** [comment]
@Heroes84 Its a good news!
About you question, you try to install not full version. Site http://h3hota.com/en/download joked on us)
In the English version of the site only links to the incomplete version are posted
<img width="1538" alt="Снимок экрана 2020-04-19 в 22 54 15" src="https://user-images.githubusercontent.com/5230575/79698382-33d9c500-8291-11ea-9ebd-6ec4442f4054.png">
If you switch to the Russian version
<img width="1536" alt="Снимок экрана 2020-04-19 в 22 54 26" src="https://user-images.githubusercontent.com/5230575/79698415-76030680-8291-11ea-8641-b61e9ca05059.png">
Added an additional block with links to the full version of HoTA
<img width="1100" alt="Снимок экрана 2020-04-19 в 22 54 34" src="https://user-images.githubusercontent.com/5230575/79698428-84e9b900-8291-11ea-87aa-17957f42f764.png">
`Полная версия, устанавливается в пустую папку:` you can translate as `Full version, installed in an empty folder:`

Download and install full version and have fun! =)
